### ISSUE TITLE
Broken link to GitHub Pages version

### ISSUE THREAD

**Issue by BNewing** [ericwbailey/working-with-high-contrast-mode-talk#3]
Thank you for creating this, and publishing it!  I found this from [Adrian Roselli's post 'CSS background images & high contrast mode'](https://adrianroselli.com/2012/08/css-background-images-high-contrast-mode.html).

I was looking at the section in the README that lists ways of viewing the presentation, and noticed that the GitHub pages link isn't working - it takes me to a 404 page. I ended up using the Notist version which worked well for me, but just thought I'd flag this!

**Comment by ericwbailey** [comment]
Hi @BNewing, thanks for the head's up. I just updated the publishing branch, I think I forgot to change it when I updated `master` to use `main` instead. Could I trouble you to verify the fix on your end?

**Comment by BNewing** [comment]
It's no trouble at all! Just tested and it looks good :) thank you for responding and updating it so quickly!

**Comment by ericwbailey** [comment]
Woo! Thank you!
